### ISSUE TITLE
Error on config of widget

### ISSUE THREAD

**Issue by kieranmcn68** [altamir-junior-dias/azure-devops-extension-estimated-completed#1]
Hi,

I'm receiving the following error in Azure DevOps cloud after I've added the widget to the dashboard and I click the gear icon:
VS403684: This widget configuration reported an error: window.LoadWidget is not a function"

Thanks,

Kieran

**Comment by kieranmcn68** [comment]
![image](https://github.com/altamir-junior-dias/azure-devops-extension-estimated-completed/assets/52341098/e2a5f4b1-448c-40eb-9915-69b0a9bac644)

Here is a screenshot of what I'm seeing in both Microsoft Edge and Firefox.

**Comment by altamir-junior-dias** [comment]
Thanks for yor message. I just push a fix ti it.

**Comment by kieranmcn68** [comment]
Thanks. That has resolved the issue.
