### ISSUE TITLE
Error Gráfica Estimado x completado

### ISSUE THREAD

**Issue by HDanielM8** [altamir-junior-dias/azure-devops-extension-estimated-completed#2]
Buen Día.

La gráfica me genera error (VS403683: No se pudo cargar la contribución que describe la configuración de este widget), agradezco tu colaboración. Gracias
![Captura](https://github.com/altamir-junior-dias/azure-devops-extension-estimated-completed/assets/164083572/2ffa1e59-7dec-447a-b0c0-e94644e1fc57)

**Comment by altamir-junior-dias** [comment]
Sorry for that. I checkwd out and a certificate was expired. I just renewed
and it ver working agiam.

Altamir Junior Dias
Microsoft Certified Technology Specialist

Celular: (51) 84334687
Messenger: ***@***.***


Em ter., 19 de mar. de 2024 às 17:22, HDanielM8 ***@***.***>
escreveu:

**Comment by HDanielM8** [comment]
Perfecto, Gracias quedo solucionado el error
